from modules.certification.views import *
from modules.contact_me.views import *
from modules.info.views import *
from modules.message.views import *
from modules.mycore.views import *
from modules.project.views import *
from modules.skill.views import *
from modules.social.views import *
from modules.story.views import *
from modules.study.views import *
from modules.teach_stack.views import *
from modules.career.views import *
